app:
  env: dev
  name: admin_like_php
  des: ouer-go-atudy
  port: 9999
  logpath: /tmp/log/admin.log

cors:
  domains:
    - http://localhost:9528
  # seconds
  max_age: 5

mysql:
  master:
    host: 127.0.0.1
    port: 3306
    user: root
    password:
    db: go_study
    charset: utf8mb4
    max_idle_conns: 2
    max_open_conns: 5
    log_mode: true
    ## minutes
    conn_max_lifetime: 60


  slave:
    host: 127.0.0.1
    port: 3306
    user: root
    password:
    db: go_study
    charset: utf8mb4
    max_idle_conns: 2
    max_open_conns: 5
    log_mode: false
    ## minutes
    conn_max_lifetime: 60


admin:
  db:
    host: 127.0.0.1
    port: 3306
    user: root
    password:
    db: ebao
    charset: utf8mb4
    max_idle_conns: 2
    max_open_conns: 5
    log_mode: false
    ## minutes
    conn_max_lifetime: 60
grpc:
  servers:
    dev:
      order:
        ip: 127.0.0.1:9134
    prod:
      order:
        ip: 127.0.0.1:9134
youth:
  host: http://127.0.0.1:8088

enums:
  admin:
    session_user_info: user_info
